# patterns = {
#     "ace05-en": {
#         'Life:Die': ['Victim', 'Instrument', 'Place', 'Agent', 'Person'], 'Life:Injure': ['Victim', 'Instrument', 'Agent', 'Place'], 'Conflict:Attack': ['Victim', 'Instrument', 'Place', 'Target', 'Agent', 'Attacker'], 'Movement:Transport': ['Victim', 'Place', 'Vehicle', 'Artifact', 'Agent', 'Destination', 'Origin'], 'Transaction:Transfer-Money': ['Beneficiary', 'Giver', 'Recipient', 'Place'], 'Justice:Sue': ['Defendant', 'Plaintiff', 'Adjudicator', 'Place'], 'Justice:Convict': ['Defendant', 'Adjudicator', 'Place'], 'Justice:Sentence': ['Defendant', 'Adjudicator', 'Place'], 'Justice:Charge-Indict': ['Defendant', 'Prosecutor', 'Adjudicator', 'Place'], 'Personnel:End-Position': ['Place', 'Person', 'Entity'], 'Personnel:Start-Position': ['Place', 'Person', 'Entity'], 'Transaction:Transfer-Ownership': ['Place', 'Seller', 'Artifact', 'Beneficiary', 'Buyer'], 'Justice:Arrest-Jail': ['Person', 'Agent', 'Place'], 'Conflict:Demonstrate': ['Entity', 'Place'], 'Justice:Appeal': ['Plaintiff', 'Adjudicator', 'Place'], 'Justice:Execute': ['Person', 'Agent', 'Place'], 'Contact:Meet': ['Entity', 'Place'], 'Personnel:Nominate': ['Person', 'Agent'], 'Contact:Phone-Write': ['Entity', 'Place'], 'Personnel:Elect': ['Person', 'Entity', 'Place'], 'Justice:Release-Parole': ['Place', 'Person', 'Entity'], 'Life:Divorce': ['Person', 'Place'], 'Life:Marry': ['Person', 'Place'], 'Justice:Fine': ['Place', 'Adjudicator', 'Entity'], 'Justice:Acquit': ['Defendant', 'Adjudicator'], 'Business:End-Org': ['Place', 'Org'], 'Business:Start-Org': ['Place', 'Agent', 'Org'], 'Justice:Trial-Hearing': ['Defendant', 'Prosecutor', 'Adjudicator', 'Place'], 'Business:Declare-Bankruptcy': ['Place', 'Org'], 'Life:Be-Born': ['Person', 'Place'], 'Justice:Extradite': ['Person', 'Origin', 'Agent', 'Destination'], 'Justice:Pardon': ['Defendant', 'Adjudicator', 'Place'], 'Business:Merge-Org': ['Org']
#     }
# }

patterns = {
    "ace05-en": {
        'Life:Die': ['Person', 'Instrument', 'Victim', 'Place', 'Agent'], 'Life:Injure': ['Instrument', 'Victim', 'Place', 'Agent'], 'Conflict:Attack': ['Instrument', 'Victim', 'Attacker', 'Place', 'Target', 'Agent'], 'Movement:Transport': ['Destination', 'Victim', 'Artifact', 'Origin', 'Place', 'Agent', 'Vehicle'], 'Transaction:Transfer-Money': ['Giver', 'Recipient', 'Place', 'Beneficiary'], 'Justice:Sue': ['Defendant', 'Plaintiff', 'Place', 'Adjudicator'], 'Justice:Convict': ['Defendant', 'Place', 'Adjudicator'], 'Justice:Sentence': ['Defendant', 'Place', 'Adjudicator'], 'Justice:Charge-Indict': ['Prosecutor', 'Defendant', 'Place', 'Adjudicator'], 'Personnel:End-Position': ['Person', 'Entity', 'Place'], 'Personnel:Start-Position': ['Person', 'Entity', 'Place'], 'Transaction:Transfer-Ownership': ['Seller', 'Artifact', 'Place', 'Buyer', 'Beneficiary'], 'Justice:Arrest-Jail': ['Person', 'Place', 'Agent'], 'Conflict:Demonstrate': ['Entity', 'Place'], 'Justice:Appeal': ['Plaintiff', 'Place', 'Adjudicator'], 'Justice:Execute': ['Person', 'Place', 'Agent'], 'Contact:Meet': ['Entity', 'Place'], 'Personnel:Nominate': ['Person', 'Agent'], 'Contact:Phone-Write': ['Entity', 'Place'], 'Personnel:Elect': ['Person', 'Entity', 'Place'], 'Justice:Release-Parole': ['Person', 'Entity', 'Place'], 'Life:Divorce': ['Person', 'Place'], 'Life:Marry': ['Person', 'Place'], 'Justice:Fine': ['Entity', 'Place', 'Adjudicator'], 'Justice:Acquit': ['Defendant', 'Adjudicator'], 'Business:End-Org': ['Org', 'Place'], 'Business:Start-Org': ['Org', 'Place', 'Agent'], 'Justice:Trial-Hearing': ['Prosecutor', 'Defendant', 'Place', 'Adjudicator'], 'Business:Declare-Bankruptcy': ['Org', 'Place'], 'Life:Be-Born': ['Person', 'Place'], 'Justice:Extradite': ['Person', 'Destination', 'Origin', 'Agent'], 'Justice:Pardon': ['Defendant', 'Place', 'Adjudicator'], 'Business:Merge-Org': ['Org']
    }
}